### ISSUE TITLE
Sposób dostarczenia aplikacji

### ISSUE THREAD

**Issue by dymanooo** [lotego-co-godo/operator-console#107]
Nasza aplikacja jest już prawie gotowa do pierwszego wydania, pozostaje tylko jedna kwestia, a mianowicie jak ją dostarczyć. Aktualnie produktem wynikowym naszego projektu są statyczne pliki strony internetowej, których nie da się uruchomić bez "servera" (np. [serve](https://www.npmjs.com/package/serve)). 

Do tego serwer dostarczony przez organizatorów hostuje api na `localhost:8080`, a żadna nowoczesna przeglądarka internetowa nie pozwoli na połączenie http z localhostem. Do tej pory korzystaliśmy z serwera proxy wbudowanego w CRA, który przekazywał wszystkie żądania na odpowiedni adres, ale nie nadaje się on do użycia na produkcji.

W jaki sposób możemy rozwiązać te problemy? Może warto byłoby spytać się organizatorów?

**Comment by rJankowski93** [comment]
W opisie projektu jest:
"Jesli do uruchomienia aplikacji beda konieczne jakies dodatkowe kroki nalezy je opisac"
więc po prostu opiszmy w dokumntacji kroki które należy zrobić, własnie np uruchomienie server itd. 
Czy dacie radę to zrobić jutro? Wtedy jutro puszczę to do organizatorów do sprawdzenia.
